version: "3"

services:
    frontend:
        build:
          context: ./frontend
          dockerfile: Dockerfile
        volumes:
          - './frontend:/app'
        ports:
          - '8000:8000'
    db:
        build:
          context: ./backend/DB
          dockerfile: Dockerfile
        volumes:
          - './backend/DB:/app'
    backend:
        # depends_on:
        #   - db
        build:
          context: ./backend
          dockerfile: Dockerfile
        volumes:
          - './backend:/app'

